version: '3'

services:
  detect:
    build: ./detect
    ports:
    - 8080:8080
  
  selector:
    build: ./selector
    ports:
    - 1997:1997
    # volumes:
    # - ./selector:/app # for dev

  bdd:
    image: postgres
    ports:
    - 5432:5432
    environment: 
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=user
    - POSTGRES_DB=hashtagbdd

  front:
    build: ./front
    ports:
    - 5000:5000